name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | tr '\\n' '\n' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/myapp
            git pull origin main

            # Stop and remove old container
            docker stop vite-app || true
            docker rm vite-app || true

            # Build and run updated container
            docker build -t vite-app .
            docker run -d --name vite-app -p 3000:80 vite-app
